version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  distobject-py-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: pytest examples/
