version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - distobject-net

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - distobject-net
    environment:
      - REDIS_HOST=redis
    command: pytest tests/

networks:
  distobject-net:
    driver: bridge
