name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker and Compose
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo apt-get install -y docker-compose-plugin

      - name: Build and run tests with Docker Compose
        run: |
          docker compose version
          docker compose up --build --abort-on-container-exit --exit-code-from test-runner
